version: '3.5'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres

  beer:
    image: beer-core
    environment:
        ConnectionStrings:DefaultConnection: User ID=postgres;Password=changeme;Server=postgres;Port=5432;Database=postgres;Integrated Security=true;Pooling=true;
    ports:
      - 5000:5000
    networks:
      - postgres

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #      - pgadmin:/root/.pgadmin
  #   ports:
  #     - 5050:80
  #   networks:
  #     - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    # pgadmin:
